---
resources:

- name: code-repository
  type: git
  source:
    uri: https://github.com/noizwaves/deployable-repo
    branch: master

- name: review-deployment
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: aneumann
    space: deployable-repo-review

jobs:
- name: build and deploy review
  plan:
  - get: code-repository
    trigger: true
  - task: build and test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: openjdk
          tag: '8-jdk'

      inputs:
      - name: code-repository

      caches:
      - path: .gradle

      run:
        path: bash
        args:
          - -exc
          - |
            cd code-repository
            ./gradlew test build

  - put: review-deployment
    params:
      manifest: code-repository/manifest-review.yml
      path: code-repository/applications/demo-server/build/libs/demo-server-*.jar